### ISSUE TITLE
CSS property for tab width

### ISSUE THREAD

**Issue by john-cj** [revin/markdown-it-expand-tabs#14]
This is not actually an issue, but by the way, in CSS, there is already property `tab-size`  ;-)

**Comment by revin** [comment]
Nice; good call. I wrote this in an effort to help build a renderer that outputs the same HTML as GitHub for a given markdown document, and at the time, they were doing a straight tabs-to-spaces transformation. I haven't checked in a while to see if that's still the case.

You're right, though; if apps can use `tab-size` (looks like there's currently [no support in the Microsoft browsers yet](https://www.caniuse.com/#search=tab-size)), that's a way nicer way to do it.
