### ISSUE TITLE
infinite loop if no `\n` in content

### ISSUE THREAD

**Issue by ashleygwilliams** [revin/markdown-it-expand-tabs#5]
if no `\n`, then `idx` is `-1` + `1` which is `0` which is `> -1`

https://github.com/revin/markdown-it-expand-tabs/blob/master/index.js#L32

found, when profiling marky on @npm's READMES, using https://github.com/npm/readme-tester

<img width="1050" alt="screen shot 2016-06-22 at 3 09 15 pm" src="https://cloud.githubusercontent.com/assets/1163554/16281115/ce10ea3a-3890-11e6-9dff-6b810fa933c9.png">

PR incoming

**Comment by revin** [comment]
oops! 😳

Thanks for the fix @ashleygwilliams, I'll get it right in.
